name: AWS CDK update check action
description: Check AWS CDK latest version and create Pull Request
author: morning-code
branding:
  icon: 'trending-up'
  color: 'green'

outputs:
  latest_version:
    description: 'AWS CDK latest version'

runs:
  using: docker
  image: docker://morningcode/aws-cdk-update-checker:latest
  entrypoint: "sh"
  args:
    - "-c"
    - "latest_version=$(aws_cdk_update_checker)"
    - "echo '::set-output name=latest_version::$latest_version'"
