name: 'AWS CDK update Pull Request Builder Github Action for TypeScript'
description: 'Check AWS CDK latest update and build pull request'

inputs:
  node-version:
    default: '16.x'
    required: false
    description: 'version of nodejs'

outputs:
  latest_version:
    description: 'AWS CDK latest version'

runs:
  using: "composite"
  steps:
    #- id: aws-cdk-update-checker
    #  name: Check AWS CDK latest release
    #  uses: morning-code/aws-cdk-update-checker@v0.0.14
    - id: aws-cdk-update-checker
      name: Check AWS CDK latest release
      uses: ./.github/actions/aws-cdk-update-checker

    - run: echo "::notice title=Output::${{ steps.aws-cdk-update-checker.outputs.latest_version }}"
      shell: bash

    - name: "Setup Node"
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}