name: 'AWS CDK update Pull Request Builder Github Action for TypeScript'
description: 'Check AWS CDK latest update and build pull request'

inputs:
  node-version:
    default: '16.x'
    required: false
    description: 'version of nodejs'

runs:
  using: "composite"
  steps:
    #- id: aws-cdk-update-checker
    #  name: Check AWS CDK latest release
    #  uses: morning-code/aws-cdk-update-checker@v0.0.14
    - id: aws-cdk-update-checker
      name: Check AWS CDK latest release
      uses: ./.github/actions/aws-cdk-update-checker

    - run: echo "latest_version=${{ steps.aws-cdk-update-checker.outputs.latest_version }}"
      shell: sh

    - name: Replace package.json
      run: sed -i -e "s/\"aws-cdk\": \"[0-9].[0-9].[0-9]\"/\"aws-cdk\": \"$(echo ${{ steps.aws-cdk-update-checker.outputs.latest_version }})\"/g" ./package.json
      shell: sh

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Update package-lock.json
      run: npm ci

   - name: Create Pull Request
     uses: peter-evans/create-pull-request@v3
     with:
       branch: fix/aws-cdk-${{ steps.aws-cdk-update-checker.outputs.latest_version }}
